# Generated by Django 3.2.13 on 2022-07-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=191)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=191)),
                ('user_name', models.TextField(max_length=191)),
            ],
        ),
    ]
