# Generated by Django 3.2.13 on 2022-09-20 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_contact_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_form',
            name='subject',
            field=models.TextField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
