# Generated by Django 3.2.13 on 2022-09-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_contact_form_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact_form',
        ),
    ]
