# Generated by Django 3.2.13 on 2022-08-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=191)),
                ('user_name', models.TextField(max_length=254)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
