# Generated by Django 3.2.13 on 2022-08-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_alter_user_activity_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_activity',
            name='text',
            field=models.TextField(),
        ),
    ]
